//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
// 
#pragma warning disable 1591

namespace EnterpriseRegistration.UserProfile.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OguReaderServiceSoap", Namespace="http://10.53.1.162")]
    public partial class OguReaderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOrganizationChildrenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOuViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetObjectsDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryOGUByConditionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersInGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupsOfUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRootDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckPwdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubjectionCustomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDirectCustomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetViewInfoByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomsCodeByUserPathOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OguReaderService() {
            this.Url = global::EnterpriseRegistration.UserProfile.Properties.Settings.Default.EnterpriseRegistration_UserProfile_WebReference_OguReaderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOrganizationChildrenCompletedEventHandler GetOrganizationChildrenCompleted;
        
        /// <remarks/>
        public event GetOuViewCompletedEventHandler GetOuViewCompleted;
        
        /// <remarks/>
        public event GetObjectsDetailCompletedEventHandler GetObjectsDetailCompleted;
        
        /// <remarks/>
        public event QueryOGUByConditionCompletedEventHandler QueryOGUByConditionCompleted;
        
        /// <remarks/>
        public event GetUsersInGroupsCompletedEventHandler GetUsersInGroupsCompleted;
        
        /// <remarks/>
        public event GetGroupsOfUsersCompletedEventHandler GetGroupsOfUsersCompleted;
        
        /// <remarks/>
        public event GetRootDepartmentCompletedEventHandler GetRootDepartmentCompleted;
        
        /// <remarks/>
        public event CheckPwdCompletedEventHandler CheckPwdCompleted;
        
        /// <remarks/>
        public event GetSubjectionCustomsCompletedEventHandler GetSubjectionCustomsCompleted;
        
        /// <remarks/>
        public event GetDirectCustomsCompletedEventHandler GetDirectCustomsCompleted;
        
        /// <remarks/>
        public event GetViewInfoByUserCompletedEventHandler GetViewInfoByUserCompleted;
        
        /// <remarks/>
        public event GetCustomsCodeByUserPathCompletedEventHandler GetCustomsCodeByUserPathCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/GetOrganizationChildren", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOrganizationChildren(string viewValue, ViewCategory viewCategory, string orgValues, OrganizationCategory orgCategory, ListObjectCategories listObjCategories, ObjectStatusCategories objectStatusCategories, int orgDepth, string orgRank, string userRank, string orgType, int orgClass, string extraAttributes) {
            object[] results = this.Invoke("GetOrganizationChildren", new object[] {
                        viewValue,
                        viewCategory,
                        orgValues,
                        orgCategory,
                        listObjCategories,
                        objectStatusCategories,
                        orgDepth,
                        orgRank,
                        userRank,
                        orgType,
                        orgClass,
                        extraAttributes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrganizationChildrenAsync(string viewValue, ViewCategory viewCategory, string orgValues, OrganizationCategory orgCategory, ListObjectCategories listObjCategories, ObjectStatusCategories objectStatusCategories, int orgDepth, string orgRank, string userRank, string orgType, int orgClass, string extraAttributes) {
            this.GetOrganizationChildrenAsync(viewValue, viewCategory, orgValues, orgCategory, listObjCategories, objectStatusCategories, orgDepth, orgRank, userRank, orgType, orgClass, extraAttributes, null);
        }
        
        /// <remarks/>
        public void GetOrganizationChildrenAsync(string viewValue, ViewCategory viewCategory, string orgValues, OrganizationCategory orgCategory, ListObjectCategories listObjCategories, ObjectStatusCategories objectStatusCategories, int orgDepth, string orgRank, string userRank, string orgType, int orgClass, string extraAttributes, object userState) {
            if ((this.GetOrganizationChildrenOperationCompleted == null)) {
                this.GetOrganizationChildrenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrganizationChildrenOperationCompleted);
            }
            this.InvokeAsync("GetOrganizationChildren", new object[] {
                        viewValue,
                        viewCategory,
                        orgValues,
                        orgCategory,
                        listObjCategories,
                        objectStatusCategories,
                        orgDepth,
                        orgRank,
                        userRank,
                        orgType,
                        orgClass,
                        extraAttributes}, this.GetOrganizationChildrenOperationCompleted, userState);
        }
        
        private void OnGetOrganizationChildrenOperationCompleted(object arg) {
            if ((this.GetOrganizationChildrenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrganizationChildrenCompleted(this, new GetOrganizationChildrenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/GetOuView", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOuView(string viewValues, ViewCategory viewCategory) {
            object[] results = this.Invoke("GetOuView", new object[] {
                        viewValues,
                        viewCategory});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOuViewAsync(string viewValues, ViewCategory viewCategory) {
            this.GetOuViewAsync(viewValues, viewCategory, null);
        }
        
        /// <remarks/>
        public void GetOuViewAsync(string viewValues, ViewCategory viewCategory, object userState) {
            if ((this.GetOuViewOperationCompleted == null)) {
                this.GetOuViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOuViewOperationCompleted);
            }
            this.InvokeAsync("GetOuView", new object[] {
                        viewValues,
                        viewCategory}, this.GetOuViewOperationCompleted, userState);
        }
        
        private void OnGetOuViewOperationCompleted(object arg) {
            if ((this.GetOuViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOuViewCompleted(this, new GetOuViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/GetObjectsDetail", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetObjectsDetail(string viewValue, ViewCategory viewCategory, string objValues, ObjectCategory objcetCategory, string parentOrgValues, OrganizationCategory parentOrgCategory, string extraAttributes) {
            object[] results = this.Invoke("GetObjectsDetail", new object[] {
                        viewValue,
                        viewCategory,
                        objValues,
                        objcetCategory,
                        parentOrgValues,
                        parentOrgCategory,
                        extraAttributes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetObjectsDetailAsync(string viewValue, ViewCategory viewCategory, string objValues, ObjectCategory objcetCategory, string parentOrgValues, OrganizationCategory parentOrgCategory, string extraAttributes) {
            this.GetObjectsDetailAsync(viewValue, viewCategory, objValues, objcetCategory, parentOrgValues, parentOrgCategory, extraAttributes, null);
        }
        
        /// <remarks/>
        public void GetObjectsDetailAsync(string viewValue, ViewCategory viewCategory, string objValues, ObjectCategory objcetCategory, string parentOrgValues, OrganizationCategory parentOrgCategory, string extraAttributes, object userState) {
            if ((this.GetObjectsDetailOperationCompleted == null)) {
                this.GetObjectsDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetObjectsDetailOperationCompleted);
            }
            this.InvokeAsync("GetObjectsDetail", new object[] {
                        viewValue,
                        viewCategory,
                        objValues,
                        objcetCategory,
                        parentOrgValues,
                        parentOrgCategory,
                        extraAttributes}, this.GetObjectsDetailOperationCompleted, userState);
        }
        
        private void OnGetObjectsDetailOperationCompleted(object arg) {
            if ((this.GetObjectsDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetObjectsDetailCompleted(this, new GetObjectsDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/QueryOGUByCondition", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryOGUByCondition(string viewValues, ViewCategory viewCategory, string orgValues, OrganizationCategory orgCategory, string objValue, bool isFuzzy, bool isFirstPerson, string orgRank, string userRank, int depth, ListObjectCategories listObjCategories, string extraAttributes) {
            object[] results = this.Invoke("QueryOGUByCondition", new object[] {
                        viewValues,
                        viewCategory,
                        orgValues,
                        orgCategory,
                        objValue,
                        isFuzzy,
                        isFirstPerson,
                        orgRank,
                        userRank,
                        depth,
                        listObjCategories,
                        extraAttributes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryOGUByConditionAsync(string viewValues, ViewCategory viewCategory, string orgValues, OrganizationCategory orgCategory, string objValue, bool isFuzzy, bool isFirstPerson, string orgRank, string userRank, int depth, ListObjectCategories listObjCategories, string extraAttributes) {
            this.QueryOGUByConditionAsync(viewValues, viewCategory, orgValues, orgCategory, objValue, isFuzzy, isFirstPerson, orgRank, userRank, depth, listObjCategories, extraAttributes, null);
        }
        
        /// <remarks/>
        public void QueryOGUByConditionAsync(string viewValues, ViewCategory viewCategory, string orgValues, OrganizationCategory orgCategory, string objValue, bool isFuzzy, bool isFirstPerson, string orgRank, string userRank, int depth, ListObjectCategories listObjCategories, string extraAttributes, object userState) {
            if ((this.QueryOGUByConditionOperationCompleted == null)) {
                this.QueryOGUByConditionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryOGUByConditionOperationCompleted);
            }
            this.InvokeAsync("QueryOGUByCondition", new object[] {
                        viewValues,
                        viewCategory,
                        orgValues,
                        orgCategory,
                        objValue,
                        isFuzzy,
                        isFirstPerson,
                        orgRank,
                        userRank,
                        depth,
                        listObjCategories,
                        extraAttributes}, this.QueryOGUByConditionOperationCompleted, userState);
        }
        
        private void OnQueryOGUByConditionOperationCompleted(object arg) {
            if ((this.QueryOGUByConditionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryOGUByConditionCompleted(this, new QueryOGUByConditionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/GetUsersInGroups", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUsersInGroups(string viewValue, ViewCategory viewCategory, string groupValues, GroupCategory groupCategory, string userRank, ObjectStatusCategories objectStatusCategories, string extraAttributes) {
            object[] results = this.Invoke("GetUsersInGroups", new object[] {
                        viewValue,
                        viewCategory,
                        groupValues,
                        groupCategory,
                        userRank,
                        objectStatusCategories,
                        extraAttributes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersInGroupsAsync(string viewValue, ViewCategory viewCategory, string groupValues, GroupCategory groupCategory, string userRank, ObjectStatusCategories objectStatusCategories, string extraAttributes) {
            this.GetUsersInGroupsAsync(viewValue, viewCategory, groupValues, groupCategory, userRank, objectStatusCategories, extraAttributes, null);
        }
        
        /// <remarks/>
        public void GetUsersInGroupsAsync(string viewValue, ViewCategory viewCategory, string groupValues, GroupCategory groupCategory, string userRank, ObjectStatusCategories objectStatusCategories, string extraAttributes, object userState) {
            if ((this.GetUsersInGroupsOperationCompleted == null)) {
                this.GetUsersInGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersInGroupsOperationCompleted);
            }
            this.InvokeAsync("GetUsersInGroups", new object[] {
                        viewValue,
                        viewCategory,
                        groupValues,
                        groupCategory,
                        userRank,
                        objectStatusCategories,
                        extraAttributes}, this.GetUsersInGroupsOperationCompleted, userState);
        }
        
        private void OnGetUsersInGroupsOperationCompleted(object arg) {
            if ((this.GetUsersInGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersInGroupsCompleted(this, new GetUsersInGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/GetGroupsOfUsers", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetGroupsOfUsers(string viewValue, ViewCategory viewCategory, string userValues, UserCategory userCategory, string parentOrgValue, OrganizationCategory parentOrgCategory, ObjectStatusCategories objectStatusCategories, string extraAttributes) {
            object[] results = this.Invoke("GetGroupsOfUsers", new object[] {
                        viewValue,
                        viewCategory,
                        userValues,
                        userCategory,
                        parentOrgValue,
                        parentOrgCategory,
                        objectStatusCategories,
                        extraAttributes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupsOfUsersAsync(string viewValue, ViewCategory viewCategory, string userValues, UserCategory userCategory, string parentOrgValue, OrganizationCategory parentOrgCategory, ObjectStatusCategories objectStatusCategories, string extraAttributes) {
            this.GetGroupsOfUsersAsync(viewValue, viewCategory, userValues, userCategory, parentOrgValue, parentOrgCategory, objectStatusCategories, extraAttributes, null);
        }
        
        /// <remarks/>
        public void GetGroupsOfUsersAsync(string viewValue, ViewCategory viewCategory, string userValues, UserCategory userCategory, string parentOrgValue, OrganizationCategory parentOrgCategory, ObjectStatusCategories objectStatusCategories, string extraAttributes, object userState) {
            if ((this.GetGroupsOfUsersOperationCompleted == null)) {
                this.GetGroupsOfUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupsOfUsersOperationCompleted);
            }
            this.InvokeAsync("GetGroupsOfUsers", new object[] {
                        viewValue,
                        viewCategory,
                        userValues,
                        userCategory,
                        parentOrgValue,
                        parentOrgCategory,
                        objectStatusCategories,
                        extraAttributes}, this.GetGroupsOfUsersOperationCompleted, userState);
        }
        
        private void OnGetGroupsOfUsersOperationCompleted(object arg) {
            if ((this.GetGroupsOfUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupsOfUsersCompleted(this, new GetGroupsOfUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/GetRootDepartment", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRootDepartment(string viewValue, ViewCategory viewCategory, string extraAttributes) {
            object[] results = this.Invoke("GetRootDepartment", new object[] {
                        viewValue,
                        viewCategory,
                        extraAttributes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRootDepartmentAsync(string viewValue, ViewCategory viewCategory, string extraAttributes) {
            this.GetRootDepartmentAsync(viewValue, viewCategory, extraAttributes, null);
        }
        
        /// <remarks/>
        public void GetRootDepartmentAsync(string viewValue, ViewCategory viewCategory, string extraAttributes, object userState) {
            if ((this.GetRootDepartmentOperationCompleted == null)) {
                this.GetRootDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRootDepartmentOperationCompleted);
            }
            this.InvokeAsync("GetRootDepartment", new object[] {
                        viewValue,
                        viewCategory,
                        extraAttributes}, this.GetRootDepartmentOperationCompleted, userState);
        }
        
        private void OnGetRootDepartmentOperationCompleted(object arg) {
            if ((this.GetRootDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRootDepartmentCompleted(this, new GetRootDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/CheckPwd", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckPwd(string identityName, string identityType, string userPwd) {
            object[] results = this.Invoke("CheckPwd", new object[] {
                        identityName,
                        identityType,
                        userPwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPwdAsync(string identityName, string identityType, string userPwd) {
            this.CheckPwdAsync(identityName, identityType, userPwd, null);
        }
        
        /// <remarks/>
        public void CheckPwdAsync(string identityName, string identityType, string userPwd, object userState) {
            if ((this.CheckPwdOperationCompleted == null)) {
                this.CheckPwdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPwdOperationCompleted);
            }
            this.InvokeAsync("CheckPwd", new object[] {
                        identityName,
                        identityType,
                        userPwd}, this.CheckPwdOperationCompleted, userState);
        }
        
        private void OnCheckPwdOperationCompleted(object arg) {
            if ((this.CheckPwdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPwdCompleted(this, new CheckPwdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/GetSubjectionCustoms", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSubjectionCustoms(string viewValue, ViewCategory viewCategory, string objValues, ObjectCategory objCategory, string parentOrgValue, OrganizationCategory parentOrgCategory, string extraAttributes) {
            object[] results = this.Invoke("GetSubjectionCustoms", new object[] {
                        viewValue,
                        viewCategory,
                        objValues,
                        objCategory,
                        parentOrgValue,
                        parentOrgCategory,
                        extraAttributes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSubjectionCustomsAsync(string viewValue, ViewCategory viewCategory, string objValues, ObjectCategory objCategory, string parentOrgValue, OrganizationCategory parentOrgCategory, string extraAttributes) {
            this.GetSubjectionCustomsAsync(viewValue, viewCategory, objValues, objCategory, parentOrgValue, parentOrgCategory, extraAttributes, null);
        }
        
        /// <remarks/>
        public void GetSubjectionCustomsAsync(string viewValue, ViewCategory viewCategory, string objValues, ObjectCategory objCategory, string parentOrgValue, OrganizationCategory parentOrgCategory, string extraAttributes, object userState) {
            if ((this.GetSubjectionCustomsOperationCompleted == null)) {
                this.GetSubjectionCustomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubjectionCustomsOperationCompleted);
            }
            this.InvokeAsync("GetSubjectionCustoms", new object[] {
                        viewValue,
                        viewCategory,
                        objValues,
                        objCategory,
                        parentOrgValue,
                        parentOrgCategory,
                        extraAttributes}, this.GetSubjectionCustomsOperationCompleted, userState);
        }
        
        private void OnGetSubjectionCustomsOperationCompleted(object arg) {
            if ((this.GetSubjectionCustomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubjectionCustomsCompleted(this, new GetSubjectionCustomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/GetDirectCustoms", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDirectCustoms(string viewValue, ViewCategory viewCategory, string objValues, ObjectCategory objCategory, string parentOrgValue, OrganizationCategory parentOrgCategory, string extraAttributes) {
            object[] results = this.Invoke("GetDirectCustoms", new object[] {
                        viewValue,
                        viewCategory,
                        objValues,
                        objCategory,
                        parentOrgValue,
                        parentOrgCategory,
                        extraAttributes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDirectCustomsAsync(string viewValue, ViewCategory viewCategory, string objValues, ObjectCategory objCategory, string parentOrgValue, OrganizationCategory parentOrgCategory, string extraAttributes) {
            this.GetDirectCustomsAsync(viewValue, viewCategory, objValues, objCategory, parentOrgValue, parentOrgCategory, extraAttributes, null);
        }
        
        /// <remarks/>
        public void GetDirectCustomsAsync(string viewValue, ViewCategory viewCategory, string objValues, ObjectCategory objCategory, string parentOrgValue, OrganizationCategory parentOrgCategory, string extraAttributes, object userState) {
            if ((this.GetDirectCustomsOperationCompleted == null)) {
                this.GetDirectCustomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDirectCustomsOperationCompleted);
            }
            this.InvokeAsync("GetDirectCustoms", new object[] {
                        viewValue,
                        viewCategory,
                        objValues,
                        objCategory,
                        parentOrgValue,
                        parentOrgCategory,
                        extraAttributes}, this.GetDirectCustomsOperationCompleted, userState);
        }
        
        private void OnGetDirectCustomsOperationCompleted(object arg) {
            if ((this.GetDirectCustomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDirectCustomsCompleted(this, new GetDirectCustomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/GetViewInfoByUser", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetViewInfoByUser(string userValue, UserCategory userCategory, bool isIncludeDisabledViews) {
            object[] results = this.Invoke("GetViewInfoByUser", new object[] {
                        userValue,
                        userCategory,
                        isIncludeDisabledViews});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetViewInfoByUserAsync(string userValue, UserCategory userCategory, bool isIncludeDisabledViews) {
            this.GetViewInfoByUserAsync(userValue, userCategory, isIncludeDisabledViews, null);
        }
        
        /// <remarks/>
        public void GetViewInfoByUserAsync(string userValue, UserCategory userCategory, bool isIncludeDisabledViews, object userState) {
            if ((this.GetViewInfoByUserOperationCompleted == null)) {
                this.GetViewInfoByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetViewInfoByUserOperationCompleted);
            }
            this.InvokeAsync("GetViewInfoByUser", new object[] {
                        userValue,
                        userCategory,
                        isIncludeDisabledViews}, this.GetViewInfoByUserOperationCompleted, userState);
        }
        
        private void OnGetViewInfoByUserOperationCompleted(object arg) {
            if ((this.GetViewInfoByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetViewInfoByUserCompleted(this, new GetViewInfoByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.53.1.162/GetCustomsCodeByUserPath", RequestNamespace="http://10.53.1.162", ResponseNamespace="http://10.53.1.162", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCustomsCodeByUserPath(string UserPath) {
            object[] results = this.Invoke("GetCustomsCodeByUserPath", new object[] {
                        UserPath});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomsCodeByUserPathAsync(string UserPath) {
            this.GetCustomsCodeByUserPathAsync(UserPath, null);
        }
        
        /// <remarks/>
        public void GetCustomsCodeByUserPathAsync(string UserPath, object userState) {
            if ((this.GetCustomsCodeByUserPathOperationCompleted == null)) {
                this.GetCustomsCodeByUserPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomsCodeByUserPathOperationCompleted);
            }
            this.InvokeAsync("GetCustomsCodeByUserPath", new object[] {
                        UserPath}, this.GetCustomsCodeByUserPathOperationCompleted, userState);
        }
        
        private void OnGetCustomsCodeByUserPathOperationCompleted(object arg) {
            if ((this.GetCustomsCodeByUserPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomsCodeByUserPathCompleted(this, new GetCustomsCodeByUserPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.53.1.162")]
    public enum ViewCategory {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        ViewCode = 2,
        
        /// <remarks/>
        ViewGuid = 4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.53.1.162")]
    public enum OrganizationCategory {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OrgGuid,
        
        /// <remarks/>
        OrgOriginalSort,
        
        /// <remarks/>
        OrgAllPathName,
        
        /// <remarks/>
        OrgGlobalSort,
        
        /// <remarks/>
        OrgCustomsCode,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.53.1.162")]
    public enum ListObjectCategories {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Organizations = 2,
        
        /// <remarks/>
        Users = 4,
        
        /// <remarks/>
        Groups = 8,
        
        /// <remarks/>
        Sideline = 16,
        
        /// <remarks/>
        All = 32,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.53.1.162")]
    public enum ObjectStatusCategories {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Common = 2,
        
        /// <remarks/>
        DirectLogic = 4,
        
        /// <remarks/>
        ConjunctOrgLogic = 8,
        
        /// <remarks/>
        ConjunctUserLogic = 16,
        
        /// <remarks/>
        All = 32,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.53.1.162")]
    public enum ObjectCategory {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OrgGuid,
        
        /// <remarks/>
        OrgOriginalSort,
        
        /// <remarks/>
        OrgAllPathName,
        
        /// <remarks/>
        OrgGlobalSort,
        
        /// <remarks/>
        OrgCustomsCode,
        
        /// <remarks/>
        UserGuid,
        
        /// <remarks/>
        UserOriginalSort,
        
        /// <remarks/>
        UserAllPathName,
        
        /// <remarks/>
        UserGlobalSort,
        
        /// <remarks/>
        UserIdentity,
        
        /// <remarks/>
        GroupGuid,
        
        /// <remarks/>
        GroupOriginalSort,
        
        /// <remarks/>
        GroupAllPathName,
        
        /// <remarks/>
        GroupGlobalSort,
        
        /// <remarks/>
        Guid,
        
        /// <remarks/>
        OriginalSort,
        
        /// <remarks/>
        AllPathName,
        
        /// <remarks/>
        GlobalSort,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.53.1.162")]
    public enum GroupCategory {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        GroupGuid,
        
        /// <remarks/>
        GroupOriginalSort,
        
        /// <remarks/>
        GroupAllPathName,
        
        /// <remarks/>
        GroupGlobalSort,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.53.1.162")]
    public enum UserCategory {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        UserGuid,
        
        /// <remarks/>
        UserOriginalSort,
        
        /// <remarks/>
        UserAllPathName,
        
        /// <remarks/>
        UserGlobalSort,
        
        /// <remarks/>
        UserIdentity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetOrganizationChildrenCompletedEventHandler(object sender, GetOrganizationChildrenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrganizationChildrenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrganizationChildrenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetOuViewCompletedEventHandler(object sender, GetOuViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOuViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOuViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetObjectsDetailCompletedEventHandler(object sender, GetObjectsDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetObjectsDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetObjectsDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryOGUByConditionCompletedEventHandler(object sender, QueryOGUByConditionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryOGUByConditionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryOGUByConditionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUsersInGroupsCompletedEventHandler(object sender, GetUsersInGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersInGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersInGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGroupsOfUsersCompletedEventHandler(object sender, GetGroupsOfUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupsOfUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupsOfUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetRootDepartmentCompletedEventHandler(object sender, GetRootDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRootDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRootDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CheckPwdCompletedEventHandler(object sender, CheckPwdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPwdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPwdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSubjectionCustomsCompletedEventHandler(object sender, GetSubjectionCustomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubjectionCustomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubjectionCustomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDirectCustomsCompletedEventHandler(object sender, GetDirectCustomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDirectCustomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDirectCustomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetViewInfoByUserCompletedEventHandler(object sender, GetViewInfoByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetViewInfoByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetViewInfoByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCustomsCodeByUserPathCompletedEventHandler(object sender, GetCustomsCodeByUserPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomsCodeByUserPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomsCodeByUserPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591