//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
// 
#pragma warning disable 1591

namespace EnterpriseRegistration.Web.WebEntReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebEntAccessSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class WebEntAccess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEntAccessDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebEntAccess() {
            this.Url = global::EnterpriseRegistration.Web.Properties.Settings.Default.EnterpriseRegistration_Web_WebEntReference_WebEntAccess;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetEntAccessDataCompletedEventHandler GetEntAccessDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEntAccessData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetEntAccessData(EntAccessDateClass EntAccess) {
            object[] results = this.Invoke("GetEntAccessData", new object[] {
                        EntAccess});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEntAccessDataAsync(EntAccessDateClass EntAccess) {
            this.GetEntAccessDataAsync(EntAccess, null);
        }
        
        /// <remarks/>
        public void GetEntAccessDataAsync(EntAccessDateClass EntAccess, object userState) {
            if ((this.GetEntAccessDataOperationCompleted == null)) {
                this.GetEntAccessDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEntAccessDataOperationCompleted);
            }
            this.InvokeAsync("GetEntAccessData", new object[] {
                        EntAccess}, this.GetEntAccessDataOperationCompleted, userState);
        }
        
        private void OnGetEntAccessDataOperationCompleted(object arg) {
            if ((this.GetEntAccessDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEntAccessDataCompleted(this, new GetEntAccessDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntAccessDateClass {
        
        private string mASTER_CUSTOMSField;
        
        private string tRADE_NAMEField;
        
        private string eNT_ABBREVIATIONField;
        
        private string tRADE_CODEField;
        
        private string bUSINESS_TYPEField;
        
        private string eNT_TYPEField;
        
        private string iS_ENTABROADField;
        
        private string oRG_CODEField;
        
        private string lEGAL_PERSONField;
        
        private string lEGAL_IDCARDField;
        
        private string bUSINESS_LICENSENOField;
        
        private string tAX_REGISTRATION_CODEField;
        
        private string eNT_PHONEField;
        
        private string eNT_PERSONField;
        
        private string eNT_ADDRField;
        
        private string nETWORK_NAMEField;
        
        private string nETWORK_WEBSITEField;
        
        private string lOG_TRACK_WEBSITEField;
        
        private string nOTEField;
        
        /// <remarks/>
        public string MASTER_CUSTOMS {
            get {
                return this.mASTER_CUSTOMSField;
            }
            set {
                this.mASTER_CUSTOMSField = value;
            }
        }
        
        /// <remarks/>
        public string TRADE_NAME {
            get {
                return this.tRADE_NAMEField;
            }
            set {
                this.tRADE_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string ENT_ABBREVIATION {
            get {
                return this.eNT_ABBREVIATIONField;
            }
            set {
                this.eNT_ABBREVIATIONField = value;
            }
        }
        
        /// <remarks/>
        public string TRADE_CODE {
            get {
                return this.tRADE_CODEField;
            }
            set {
                this.tRADE_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string BUSINESS_TYPE {
            get {
                return this.bUSINESS_TYPEField;
            }
            set {
                this.bUSINESS_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string ENT_TYPE {
            get {
                return this.eNT_TYPEField;
            }
            set {
                this.eNT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string IS_ENTABROAD {
            get {
                return this.iS_ENTABROADField;
            }
            set {
                this.iS_ENTABROADField = value;
            }
        }
        
        /// <remarks/>
        public string ORG_CODE {
            get {
                return this.oRG_CODEField;
            }
            set {
                this.oRG_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string LEGAL_PERSON {
            get {
                return this.lEGAL_PERSONField;
            }
            set {
                this.lEGAL_PERSONField = value;
            }
        }
        
        /// <remarks/>
        public string LEGAL_IDCARD {
            get {
                return this.lEGAL_IDCARDField;
            }
            set {
                this.lEGAL_IDCARDField = value;
            }
        }
        
        /// <remarks/>
        public string BUSINESS_LICENSENO {
            get {
                return this.bUSINESS_LICENSENOField;
            }
            set {
                this.bUSINESS_LICENSENOField = value;
            }
        }
        
        /// <remarks/>
        public string TAX_REGISTRATION_CODE {
            get {
                return this.tAX_REGISTRATION_CODEField;
            }
            set {
                this.tAX_REGISTRATION_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string ENT_PHONE {
            get {
                return this.eNT_PHONEField;
            }
            set {
                this.eNT_PHONEField = value;
            }
        }
        
        /// <remarks/>
        public string ENT_PERSON {
            get {
                return this.eNT_PERSONField;
            }
            set {
                this.eNT_PERSONField = value;
            }
        }
        
        /// <remarks/>
        public string ENT_ADDR {
            get {
                return this.eNT_ADDRField;
            }
            set {
                this.eNT_ADDRField = value;
            }
        }
        
        /// <remarks/>
        public string NETWORK_NAME {
            get {
                return this.nETWORK_NAMEField;
            }
            set {
                this.nETWORK_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string NETWORK_WEBSITE {
            get {
                return this.nETWORK_WEBSITEField;
            }
            set {
                this.nETWORK_WEBSITEField = value;
            }
        }
        
        /// <remarks/>
        public string LOG_TRACK_WEBSITE {
            get {
                return this.lOG_TRACK_WEBSITEField;
            }
            set {
                this.lOG_TRACK_WEBSITEField = value;
            }
        }
        
        /// <remarks/>
        public string NOTE {
            get {
                return this.nOTEField;
            }
            set {
                this.nOTEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetEntAccessDataCompletedEventHandler(object sender, GetEntAccessDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEntAccessDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEntAccessDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591